import { describe, it, expect } from 'vitest';
import {
  WideCreationService,
  WideCreationTemplate,
} from '../../src/services/draft/WideCreationService';
import {
  VALID_OPTIMIZATION_GOALS,
  VALID_DESTINATION_TYPES,
  OBJECTIVE_DEFAULTS,
  PROMOTED_OBJECT_REQUIREMENTS,
  BID_CAP_STRATEGIES,
  ATTRIBUTION_SPEC_OBJECTIVES,
} from '../../src/services/draft/MetaFieldRegistry';
import { FieldOptimizationEngine } from '../../src/services/draft/FieldOptimizationEngine';
import { validateAgainstContract, CAMPAIGN_CONTRACT, ADSET_CONTRACT, AD_CONTRACT } from '../contracts/meta-api-contracts';

const ALL_OBJECTIVES = Object.keys(VALID_OPTIMIZATION_GOALS);

// ─── Generated Payloads Meet Meta Contracts ───
// Tests that the payloads generated by wide creation would pass Meta API validation.
// We simulate generate by manually building the payloads the same way the service does.

describe('Wide Creation → Meta Contract Validation', () => {
  for (const objective of ALL_OBJECTIVES) {
    describe(`${objective}`, () => {
      const defaults = OBJECTIVE_DEFAULTS[objective];
      const promotedReqs = PROMOTED_OBJECT_REQUIREMENTS[objective] || [];

      it('generated campaign payload matches campaign contract', () => {
        const campaignPayload = {
          name: `Wide ${objective} Campaign`,
          objective,
          status: 'PAUSED',
          special_ad_categories: ['NONE'],
          daily_budget: '5000',
        };
        const violations = validateAgainstContract(campaignPayload, CAMPAIGN_CONTRACT);
        expect(violations).toEqual([]);
      });

      it('generated adset payload matches adset contract', () => {
        const adSetPayload: Record<string, any> = {
          name: `Wide ${objective} AdSet`,
          campaign_id: '12345',
          optimization_goal: defaults.optimization_goal,
          billing_event: defaults.billing_event,
          destination_type: defaults.destination_type,
          targeting: { geo_locations: { countries: ['TH'] } },
          status: 'PAUSED',
        };

        if (promotedReqs.length > 0) {
          adSetPayload.promoted_object = { [promotedReqs[0]]: '12345678' };
        }

        const violations = validateAgainstContract(adSetPayload, ADSET_CONTRACT, { objective });
        const real = violations.filter(v => !['end_time', 'bid_amount'].includes(v.field));
        expect(real).toEqual([]);
      });

      it('generated ad payload matches ad contract', () => {
        const adPayload = {
          name: `Wide ${objective} Ad`,
          adset_id: '12345',
          status: 'PAUSED',
          creative: { creative_id: '99999' },
        };
        const violations = validateAgainstContract(adPayload, AD_CONTRACT);
        expect(violations).toEqual([]);
      });
    });
  }
});

// ─── Wide Creation Optimization Integration ───
// Tests that wide-generated payloads can be run through FieldOptimizationEngine

describe('Wide Creation → FieldOptimizationEngine Compatibility', () => {
  for (const objective of ALL_OBJECTIVES) {
    const defaults = OBJECTIVE_DEFAULTS[objective];
    const promotedReqs = PROMOTED_OBJECT_REQUIREMENTS[objective] || [];

    it(`${objective}: generated campaign can be re-optimized`, () => {
      const campaignPayload = {
        name: `Wide ${objective}`,
        objective,
        status: 'PAUSED',
        special_ad_categories: ['NONE'],
        daily_budget: '5000',
      };
      const result = FieldOptimizationEngine.optimizeCampaignForDuplication(campaignPayload);
      expect(result.errors).toHaveLength(0);
      expect(result.payload.objective).toBe(objective);
    });

    it(`${objective}: generated adset can be re-optimized (non-CBO)`, () => {
      const adSetPayload: Record<string, any> = {
        name: `Wide ${objective} AdSet`,
        optimization_goal: defaults.optimization_goal,
        billing_event: defaults.billing_event,
        destination_type: defaults.destination_type,
        targeting: { geo_locations: { countries: ['TH'] } },
        daily_budget: '3000',
      };
      if (promotedReqs.length > 0) {
        adSetPayload.promoted_object = { [promotedReqs[0]]: '12345' };
      }

      const result = FieldOptimizationEngine.optimizeAdSetForDuplication(adSetPayload, objective, false);
      expect(result.errors).toHaveLength(0);
      expect(VALID_OPTIMIZATION_GOALS[objective]).toContain(result.payload.optimization_goal);
    });

    it(`${objective}: generated adset can be re-optimized (CBO)`, () => {
      const adSetPayload: Record<string, any> = {
        name: `Wide ${objective} AdSet`,
        optimization_goal: defaults.optimization_goal,
        billing_event: defaults.billing_event,
        destination_type: defaults.destination_type,
        targeting: { geo_locations: { countries: ['TH'] } },
      };
      if (promotedReqs.length > 0) {
        adSetPayload.promoted_object = { [promotedReqs[0]]: '12345' };
      }

      const result = FieldOptimizationEngine.optimizeAdSetForDuplication(adSetPayload, objective, true);
      expect(result.errors).toHaveLength(0);
      expect(result.payload.daily_budget).toBeUndefined();
      expect(result.payload.lifetime_budget).toBeUndefined();
    });
  }
});

// ─── Inheritance + Override Scenarios ───

describe('Wide Creation Inheritance Scenarios', () => {
  it('template defaults flow through to validation without errors', () => {
    const template: WideCreationTemplate = {
      name: 'Inheritance Flow',
      adAccountId: 'act_123',
      defaults: {
        campaign: {
          bid_strategy: 'LOWEST_COST_WITHOUT_CAP',
          special_ad_categories: ['NONE'],
        },
        adSet: {
          billing_event: 'IMPRESSIONS',
          targeting: { geo_locations: { countries: ['TH', 'US'] } },
        },
        ad: {
          creative: { creative_id: '99999' },
        },
      },
      namingPattern: {
        campaign: '{objective} - {index:02d}',
        adSet: '{parent} AS-{index}',
        ad: '{parent} Ad-{index}',
      },
      campaigns: ALL_OBJECTIVES.map(obj => ({
        fields: {
          objective: obj,
          daily_budget: '5000',
        },
        adSetCount: 0,
        adSets: [{
          fields: {
            optimization_goal: OBJECTIVE_DEFAULTS[obj].optimization_goal,
            destination_type: OBJECTIVE_DEFAULTS[obj].destination_type,
            ...(PROMOTED_OBJECT_REQUIREMENTS[obj]?.length
              ? { promoted_object: { [PROMOTED_OBJECT_REQUIREMENTS[obj][0]]: '12345' } }
              : {}),
          },
          adCount: 2,
        }],
      })),
    };

    const result = WideCreationService.validateTemplate(template);
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
    expect(result.totalEntities.campaigns).toBe(6);
    expect(result.totalEntities.adSets).toBe(6);
    expect(result.totalEntities.ads).toBe(12);
  });

  it('child-level override does not affect sibling validation', () => {
    const template: WideCreationTemplate = {
      name: 'Override',
      adAccountId: 'act_123',
      defaults: {
        adSet: { optimization_goal: 'LINK_CLICKS' },
        ad: { creative: { creative_id: '99999' } },
      },
      campaigns: [{
        fields: { objective: 'OUTCOME_TRAFFIC', name: 'C' },
        adSetCount: 0,
        adSets: [
          { fields: { optimization_goal: 'LANDING_PAGE_VIEWS' }, adCount: 1 },
          { fields: {}, adCount: 1 }, // inherits LINK_CLICKS from defaults
        ],
      }],
    };
    const result = WideCreationService.validateTemplate(template);
    expect(result.valid).toBe(true);
  });
});

// ─── Budget × Bid Strategy Combinatorial ───

describe('Wide Creation Budget×Bid Combinatorial', () => {
  const bidStrategies = ['LOWEST_COST_WITHOUT_CAP', 'COST_CAP', 'LOWEST_COST_WITH_BID_CAP'];

  for (const objective of ALL_OBJECTIVES) {
    for (const bidStrategy of bidStrategies) {
      const requiresBidAmount = BID_CAP_STRATEGIES.has(bidStrategy);

      it(`${objective} / ${bidStrategy} ${requiresBidAmount ? '(errors on missing bid_amount)' : '(valid)'}`, () => {
        const template: WideCreationTemplate = {
          name: 'Bid Test',
          adAccountId: 'act_123',
          defaults: { ad: { creative: { creative_id: '99999' } } },
          campaigns: [{
            fields: { objective, name: 'C' },
            adSetCount: 0,
            adSets: [{
              fields: {
                bid_strategy: bidStrategy,
                ...(requiresBidAmount ? {} : {}),
                ...(PROMOTED_OBJECT_REQUIREMENTS[objective]?.length
                  ? { promoted_object: { [PROMOTED_OBJECT_REQUIREMENTS[objective][0]]: '12345' } }
                  : {}),
              },
              adCount: 1,
            }],
          }],
        };
        const result = WideCreationService.validateTemplate(template);
        if (requiresBidAmount) {
          expect(result.valid).toBe(false);
          expect(result.errors.some(e => e.message.includes('bid_amount'))).toBe(true);
        } else {
          expect(result.valid).toBe(true);
        }
      });
    }
  }
});

// ─── Attribution Spec Handling ───

describe('Wide Creation Attribution Spec', () => {
  for (const objective of ALL_OBJECTIVES) {
    const supported = ATTRIBUTION_SPEC_OBJECTIVES.has(objective);
    it(`${objective}: attribution_spec ${supported ? 'supported' : 'not needed'}`, () => {
      const template: WideCreationTemplate = {
        name: 'Attr',
        adAccountId: 'act_123',
        defaults: { ad: { creative: { creative_id: '99999' } } },
        campaigns: [{
          fields: { objective, name: 'C' },
          adSetCount: 0,
          adSets: [{
            fields: {
              attribution_spec: [{ event_type: 'CLICK_THROUGH', window_days: 7 }],
              ...(PROMOTED_OBJECT_REQUIREMENTS[objective]?.length
                ? { promoted_object: { [PROMOTED_OBJECT_REQUIREMENTS[objective][0]]: '12345' } }
                : {}),
            },
            adCount: 1,
          }],
        }],
      };
      const result = WideCreationService.validateTemplate(template);
      expect(result.valid).toBe(true);
    });
  }
});
